name: Build and Push MegaCMD GUI Docker Image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag for the Docker image (e.g., v1.0.0)'
        required: false
        type: string
        default: ''

env:
  IMAGE_NAME: jensheidrich76/megacmd-gui

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64, amd64
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: prepare_tags
        run: |
          TAGS="${{ env.IMAGE_NAME }}:latest"
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG_NAME="${{ github.ref }}"
            TAG_NAME="${TAG_NAME#refs/tags/}"
            TAGS="${TAGS},${{ env.IMAGE_NAME }}:${TAG_NAME}"
          fi
          if [[ ! -z "${{ github.event.inputs.version_tag }}" ]]; then
            TAGS="${TAGS},${{ env.IMAGE_NAME }}:${{ github.event.inputs.version_tag }}"
          fi
          echo "DOCKER_TAGS=${TAGS}" >> "$GITHUB_OUTPUT"
        shell: bash
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.prepare_tags.outputs.DOCKER_TAGS }}
